region: ap-northeast-1
cluster: debug_container
service: debug_container
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      path: ../terraform/terraform.tfstate

